title: Dibyajyoti Sahu
description: Theoretical Condensed Matter Physics

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# Navigation
main:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/

# Enable navigation
header:
  nav: main
